server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: test-service
        uri: lb://test
        predicates:
        - Path=/v1/**
      - id: authentication-service
        uri: lb://authentication
        predicates:
        - Path=/user/**

# custom properties
prefilter:
  ignored: /user/authenticate,/user/register,user/test
# auto config refresh enabled. to achieve this write a custom scheduler which will trigger /actuator/refresh end point 
client:
  config:
    auto-refresh:
      enabled: false
      delay: 120 # 2 mins 


    
