spring:
  cloud:
    gateway:
      # added for CORS to allow all host , methods and origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/products/**
      - id: authentication-service
        uri: lb://authentication
        predicates:
        - Path=/user/**

# custom properties
prefilter:
  ignored: /user/authenticate,/user/register
# auto config refresh enabled. to achieve this write a custom scheduler which will trigger /actuator/refresh end point 
client:
  config:
    auto-refresh:
      enabled: true
      delay: 120 # 2 mins 


    
